bump-sh/docs

docusaurus.config.js

Following the repo renaming, we broke the GitHub links.

Fix bad GitHub links

---

src/css/custom.css
src/css/markdown.css
src/css/variables.css

This makes the markdown content the same as in our docs.

style: override content styles

---

static/_redirects

This rule will redirect any help.bump.sh/* pages to the new hub
content domain docs.bump.sh/help/*. See [netlify documentation](https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file) for details about the syntax of the `_redirects` file.
Closes #1

redirects: use netlify static routing redirect rules

---

src/css/custom.css

Because it broke the footer alignement 🤷‍♀️ :

fix: restore `.container` margins and apply changes to main content container

---

docs/help/specifications-support/openapi-support/name-and-sort-resources.md

Let's remove hand written warning emoji with the “caution” callouts instead to make the important cautious content clearer for the users.

content: explicit caution about hidden operations or webhooks

---

docs/help/specifications-support/index.md
sidebars.js

- added a new home page for the specifications supported
- updated to sidebar to make the "specifications support" clickable, pointing to this page
Suggestion:
- would love to transform the bullet points into clickable cards.
- please review wording (I used "REST APIs" for instance, not sure of this)

Specifications support page

---

docs/help/doc-topics.md
docs/help/index.md
docs/help/specifications-support/asyncapi-support.md
docs/help/specifications-support/markdown-support.md
docs/help/specifications-support/openapi-support.md
sidebars.js

- quick update on home (modified wording, link and a few readability items) -- Not satisfied, need help here
- Splitted "topics" from the Markdown support page into a dedicated page ("doc-topics.md")
- modified the sidebar to group access related articles and customization options

Update on main page

---

docs/help/index.md
static/_redirects

Redirecting a root custom domain to another doesn't work well (we get a Docusaurus error instead of being redirected).
With this change, we redirect everything (including /) on /help.

Replace / by /help, and redirect until we have a real /

---

docusaurus.config.js

It was broken from the beginning for any page other than /, but it became visible because of the direct to /help.

Fix footer images src

---

docusaurus.config.js

This PR adds links to:
* https://bump.sh
* https://developers.bump.sh
Do you have any idea on other links we should display? Maybe we could add one pointing to https://github.com/bump-sh, with the GitHub icon? WDYT? Something else? 
This one follows the previously closed #33.

Add links to bump.sh and developers.bump.sh

---

docs/help/continuous-integration/github-actions.md

We should probably find a way to sync the github-action repo README
with this help page, or simply write a different content here in the
help page?
(sync https://github.com/bump-sh/github-action/pull/366)

github-action: update latest changes from README

---

docs/help/doc-topics.md
sidebars.js

The `doc-topic.md` page was not present in the sidebar.js file (making
it a page without sidebar, cf https://docs.bump.sh/help/doc-topics/).
I suggest to add a new sidebar category “Documentation
customization” (any other suggested wording by the reviewer will be
appreciate) and add this page inside it.

Nav: improve sidebar and add `doc-topic` page

---

docs/help/bump-cli.md

After some user feedback let's add some explicit reference to
branching in the `bump deploy` command documentation.
Similar to https://github.com/bump-sh/cli/pull/424

cli: add details about how to use branching during deploy

---

docs/help/continuous-integration/github-actions.md

Similarly to https://github.com/bump-sh/github-action/pull/398 we
upgrade the version of the core GH action used in our examples.

gh-action: upgrade examples with latest core gh actions

---

docs/product-updates/2022-12-07-improved-access-management.md
docs/product-updates/2023-01-27-enhanced-specifications-support.md

This commit makes sure to move content to the correct pages.

fix: two product updates were inverted (wrong title <-> URL)

---

docs/help/specifications-support/markdown-support.md

As mentionned in [this comment](https://docs.google.com/document/d/1Kk3OGx-DWg_7w5VdcTakj_6vlysblFFcJ9ja3ZxtUMs/edit?disco=AAAAwbTCQmg), Bump.sh supports images in markdown.
I've added a section that describes the usage and behaviour when adding images into documentations descriptions

markdown support: add images section

---

docs/help/bump-cli.md
docs/help/hubs.md

This feature was recently added in the [latest release of the
CLI](https://github.com/bump-sh/cli/releases/tag/v2.7.0) so we needed
to document its usage in the Bump CLI help page.
Let me know if something is unclear.

cli: add a paragraph about the folder deployment feature

---

docs/product-updates/2023-06-16-api-branch-management.md

This commit fixes a link to the “list of branches” endpoint and also
adds an extra link in the introducing paragraph to our Api documentation.

product-update: fix link and add link to Bump API

---

src/css/markdown.css

This PR updates markdown image style by adding a rounded corner, as seen below:
**before**
**after**

Markdown: Image style

---

docs/help/specifications-support/openapi-support/name-and-sort-resources.md

This label has been updated by https://github.com/bump-sh/bump/pull/3750, we forgot to update documentation.
Change is visible here:
https://deploy-preview-90--bump-content-hub.netlify.app/help/specifications-support/openapi-support/name-and-sort-resources/

Adapt default label in group_operation_by

---

docs/help/specifications-support/json-schema.md
sidebars.js

Two steps in this PR:
- Add introduction to this JSON Schema section, how it's used by both OpenAPI and AsyncAPI section
- Add more details about `enum` and `const` support
Preview is accessible here:
https://deploy-preview-88--bump-content-hub.netlify.app/help/specifications-support/json-schema/

Adapt JSON schema section

---

docs/help/getting-started/api-platform.md
docs/help/getting-started/fastapi.md

Using command `bump deploy` requires to use a parameter `token`.
This PR adapts sections How to start with ApiPlatform, and FastApi.
On the way back from ApiPlatform, I'd love to write more content about a better usecase to describe connexion between ApiPlatform and bump.sh,
This is a first step 😉

Complete 'how to' guides with token

---

frontend/styles/components/toc.css
frontend/styles/pages/help.css
src/_components/help/sidebar.css
src/_components/shared/footer.rb
src/_layouts/default.erb
src/_layouts/help.erb

This PR allows the Help page sidebar and content to be scrolled separately by fixing a max-height.
It removes the footer that made the scrolling a bit awkward.
This is a first step to a seamless sidebar when navigating through the search.

help: separate scroll for sidebar and content and remove footer

---

frontend/javascript/controllers/copy_controller.js
frontend/styles/pages/help.css
frontend/styles/typography.css
plugins/builders/inspectors.rb
src/_layouts/default.erb

This PR adds a builder that automatically applies a link to content headings that can be copied on click.

help: add anchor link to headings

---

src/_help/continuous-integration/github-actions.md

Copy new documentation information from the [Github-Action repo readme](https://github.com/bump-sh/github-action/blob/master/README.md)

github-action: sync with repo README.md

---

src/_data/sidebar.yml

Moving that part down in the sidebar makes more sense and takes "less" reading space.

move down support spec section for lisibility and logic flow

---

plugins/builders/sidebar.rb
src/_components/help/sidebar.erb
src/_components/help/sidebar.rb
src/_components/help/sidebar/item.css
src/_components/help/sidebar/item.erb
src/_components/help/sidebar/item.rb
src/_data/sidebar.yml
src/_layouts/help.erb

Building the sidebar object in a builder so it gets executed only once. Thanks to this, we go from a 24s building time to 4s.
Also I removed the field `type` in `sidebar.yml`, we will rely on the presence of items to determine if they're a sub menu.
It seems it doesn't change the small lag when visiting the docs for the first time but it will be more comfortable when editing files.

help: improve sidebar performances

---

frontend/javascript/controllers/sidebar_controller.js
frontend/styles/atoms/button.css
src/_components/help/sidebar.css
src/_components/help/sidebar.erb
src/_components/help/sidebar/item.css
src/_components/help/sidebar/item.erb
src/_components/help/sidebar/item.rb
src/images/icons/caret-right.svg

Adds a button on the side of parent items.
Items are collapsed by default unless they're the current page or parent to the current page.
If parent is not an actual page but just a category (cf _Documentation customization_ or _Account_), clicking it will expand the item list as well. However, they will not turn blue on hover.
Tell me what you think about it!

docs: make categories collapsible

---

bridgetown.config.yml
netlify.toml
src/_redirects

The `_redirects` file is simple to use/maintain than the global config file to handle redirections.
This PR also re-activate the help.bump.sh/* -> docs.bump.sh/* global redirection.

Use Netlify _redirects file instead of the main config file

---

src/_redirects

The previous `_redirects` global redirection from help.bump.sh was for SEO and was specific for our Docusaurus migration.
Now, we just want to redirect help.bump.sh/* to docs.bump.sh/*.

Fix help.bump.sh redirects

---

src/_components/shared/third_parties.erb
src/_components/shared/third_parties.rb
src/_layouts/default.erb

Forgot to restore third party apps when switching to the new content hub, oops!

restore fathom and intercom

---

README.md

This should be of use for our GTM team and external contributors on how guides should be added, especially on frolder structure and frontmatter data.

add a paragraph on how to contribute to guides

---

frontend/styles/pages/category.css
frontend/styles/pages/guides.css
src/_components/guides/category/section.erb
src/_components/guides/category/section.rb
src/_components/guides/list.css
src/_components/guides/list.erb
src/_components/guides/list.rb
src/_pages/guides/category.erb
src/images/icons/arrow-right-circle.svg

* sets the number of displayed guides by category to 3
* moves links to categories from header to card list

guides: reduce guide number and change link to categories style

---

frontend/styles/pages/help.css

Changed the size of the `h3` element that was too close from `h2`, though the difference now is still light, maybe we should make headings more differents?

make h3 smaller for better differentiation with h2

---

frontend/styles/pages/category.css
frontend/styles/pages/guides.css
plugins/builders/helpers.rb
src/_components/categories/sidebar.css
src/_components/categories/sidebar.erb
src/_components/categories/sidebar.rb
src/_components/categories/sidebar/item.erb
src/_components/categories/sidebar/item.rb
src/_components/guides/list.css
src/_components/guides/list.erb
src/_components/guides/sidebar.erb
src/_components/guides/taglist.erb
src/_components/guides/taglist.rb
src/_components/shared/hero.css
src/_components/shared/hero.erb
src/_layouts/guides.erb
src/_pages/guides/category.erb

This PR adds a list of tags under the Guides page header so users can navigate easily through categories.

guides: show category list

---

src/_help/bump-cli.md

These changes of the Bump-CLI page are similar to the changes
suggested on the CLI repository: https://github.com/bump-sh/cli/pull/543

help(bump-cli): sync with the latest changes of README of cli repo

---

src/_help/publish-documentation/branching.md

In the branching page of the help, we mention how to deploy to Bump.sh
using the CLI or the API. However we don't mention the Github-Action,
which is our first recommended way to deploy to Bump.sh (if the user
uses github of course) so I've added a paragraph about that.

help(branching): add a paragraph about the Github-Action

---

src/_data/sidebar.yml
src/_help/continuous-integration/ci.md
src/_help/continuous-integration/index.md
src/_help/getting-started/concepts.md

As discussed with Seb, it feels better to have a dedicated page for
“All other CI tools” where we can detail the usage of our suggested
configuration files for CI systems that are different than GitHub
Action.
We could improve this new page, but this is my early contribution to
this new re-arragement of the docs.

section(ci): move some bits and add a dedicated “CI” page

---

README.md
src/_guides/bump-sh-tutorials/api-platform.md
src/_guides/bump-sh-tutorials/fastapi.md
src/_guides/bump-sh-tutorials/huma.md

When making ordered lists, numbers will not be contiguous if blocks are added with an empty line after the paragraph so this is more of a copy issue here (or a kramdown issue depending on what you find more convenient).
Guides will be fixed by removing this empty line and setting the right indentation to blocks.
Also added an entry in the contributing guide to help understanding the issue.
Fixes #159

fix list numbers when adding block in between

---

src/_guides/openapi/code-first-rails.md

This commit contains a few suggestions:
- removing white spaces
- Adding a prerequesite sentence to assume the users uses `RSpec`
- Moving the “deploying to bump.sh” laius inside a callout blockquote
- Adding a multiline description for the `Cache-Control` header to
show the power of markdown in the generated docs

guides: suggestions on a recently merged guide on code-first Rails

---

src/_guides/openapi/design-first-laravel-php.md

This is a rough draft, as in its functionally complete but the wording is probably not great especially towards the end. If you folks can make pointers and feedback to stuff you like or don't I'll get it fixed up.

Guide: Design First Laravel 

---

src/_guides/openapi/code-first-rails.md
src/_guides/openapi/design-first-rails.md

Sorry about this folks, I checked the merged guides and there's more formatting issues. I had fixed these in the laravel pulls but in an effort to keep PRs independent I reset them and forgot to apply the fixes in the right branch.

tweak to formatting for rails guides

---

src/_guides/technical-writing/efficient-tech-writing-process.md

This commit fixes an incorrect link which was pointing to a localhost
instance.

fix: incorrect link to another guide

---

src/_guides/technical-writing/efficient-tech-writing-process.md

This is a change as a follow-up to #194 to show a more simple (and
best Bump.sh recommended way) deploy workflow file.

guide: share a more common deployment GH action workflow

---

frontend/styles/atoms/input.css
frontend/styles/components/tasklist.css
frontend/styles/index.css

Seems like our markdown processor automatically turns checkbox lists into `task-list`s, which make them easy to style with the given classname.
I removed the bullet points from the list and gave checkboxes a smaller and square look.
(don't mind the nav, it seems firefox screenshot feature doesn't handle blur)

styles: add tasklist and checkbox basic style

---

src/_redirects

We have some dead links coming from bump.sh (both marketing page
/students and from the workspace for links to documentation about the
bump-cli).
This PR fixes those by adding redirections to the correct pages.

fix: add redirections for links which are present in the product

---

src/_help/specification-support/openapi-support.md

Follow-up to https://github.com/bump-sh/bump/pull/5012

openapi: partial support of XML generated examples

---

src/_guides/asyncapi/2024-03-25-asyncapi-first-event-driven-api.md
src/_guides/bump-sh-tutorials/2024-03-25-huma.md
src/_guides/openapi/2024-03-25-design-first-laravel-php.md
src/_guides/openapi/2024-03-25-design-first-rails.md
src/_help/continuous-integration/cli.md

We changed the name (again) in the latest release
https://github.com/bump-sh/github-action/releases/tag/v1.1.10
Let's change the GH action URL everywhere it's used.
Follow-up to https://github.com/bump-sh/docs/pull/235

Update GH action URL

---

src/_components/guides/sidebar.erb
src/_components/guides/sidebar.rb
src/_components/shared/bump_cta.erb
src/_components/shared/bump_cta.rb

@thimy is it possible to dynamically add a `utm_content` that would take the file name (minus the .md extension) of the guide from which the CTA is clicked on?

Add UTM tags to CTA

---

src/_components/guides/sidebar.css

Don't mind the header, the blur doesn't work in my screenshots.

guides: make cta sticky

---

src/_help/organizations/organization-access-management.md

Quick update on SSO page reflecting the latest changes from Polo

Updated SSO help page based on latest modification

---

frontend/styles/atoms/button.css
src/_components/shared/highlight_banner.css
src/_components/shared/highlight_banner.erb
src/_components/shared/highlight_banner.rb
src/_layouts/guides.erb

This component will let us highlight the OpenAPI guides or any other kind of content.
What it will look like:

create a component for a highlight banner

---

src/_components/shared/bump_cta.css
src/_components/shared/bump_cta.erb

Changed the prompt, added caps and centered button content.

cta: edit text and make button content centered

---

src/_components/shared/page_navigation.css
src/_components/shared/page_navigation.erb
src/_components/shared/page_navigation.rb

This component takes the list of resources of a collection, creates a flat array of all the resources to find the previous and next pages to display below a post.
It should be integrated in the upcoming OpenAPI guides and will look like this:

component: prev/next navigation

---

src/_components/shared/nav/item.css
src/_components/shared/nav/item.erb
src/_components/shared/nav/item.rb
src/_components/shared/navbar.css
src/_components/shared/navbar.erb
src/_components/shared/navbar.rb
src/_data/navbar.yml
src/_layouts/default.erb
src/_pages/guides.md

Based on the three collections “help”, “guides” and “product-updates”
this commit adds a CSS property `active` on the active category in the
top navigation bar.
Visually I've simply added an underlined text decoration (but fill
free to suggest something else).
<details>
<summary>before</summary>
</details>
<details>
<summary>after</summary>
</details>
Part of #193

nav: set the active item on the top navigation

---

src/_guides/bump-sh-tutorials/mocking-with-microcks.md

Hi Bump team!
Thanks for writing this article. It is really good, with simple and comprehensive explanations of Microcks' templating features. Great job!
I fixed some minor typos and suggested adding a link to the reference of supported API artifacts.
Keep up the great work!

Fix some typos + add a link on Mocking with Microcks tutorial

---

src/_guides/openapi/specification/_defaults.yml

Added an option to exclude specification guides from being listed in the OpenAPI list.

specification guides: exclude from listing

---

src/_guides/openapi/accelerating-youropenapi-spec-generation-with-typespec.md

Added the missing canonical url to this article.

Canonical URL for OpenAPI spec generation with Typespec

---

src/_help/specification-support/asyncapi-support.md

This PR simply clarifies that we support AsyncAPI up to version 2.6 and invites users interested in version 3.0 to reach out via email.

AsyncAPI support update

---

src/_help/organizations/organization-access-management.md

A section of the help documentation on SSO has been updated to reflect recent changes.

Remove outdated information about SSO from Help Center

---

src/_guides/bump-sh-tutorials/try-requests-in-insomnia.md
src/_guides/bump-sh-tutorials/try-requests-in-postman.md
src/_guides/openapi/specification/v3.1/introduction/benefits.md
src/_guides/technical-writing/api-documentation-checklist.md
src/_guides/technical-writing/the-role-of-technical-writer-in-api-documentation.md

I’ve chosen to announce the availability of the new API Explorer as a callout on the relevant pages, with a link to the PU and a demo doc.
I believe I’ve covered all the relevant pages, but let me know if the wording works for you!

Add mention about Bump.sh API Explorer in relevant pages

---

src/_guides/openapi/specification/v3.1/advanced/callbacks-webhooks.md

Link to petstore example was broken, I suggest
to replace by our own documented webhook in our Api documentation.
And while here, this commit add a link to blog post article 😇

Webhook: Fix provided example link

---

src/_guides/bump-sh-tutorials/api-platform.md
src/_guides/bump-sh-tutorials/fastapi.md
src/_guides/bump-sh-tutorials/generate-sdks-with-speakeasy.md
src/_guides/openapi/specification/v3.1/extending/overlays.md
src/_guides/technical-writing/efficient-tech-writing-process.md
src/_help/continuous-integration/cli.md

Using the CLI for mutliple overlays until the GHA supports it (https://github.com/bump-sh/github-action/pull/509).

Improve guides to use multiple overlays

---

src/_components/shared/sidebar.css
src/_components/shared/sidebar.erb
src/_guides/openapi/specification/_defaults.yml
src/_layouts/documentation.erb

Purpose of this PR is to display the CTA button in guides section 'OpenAPI specification'.
I noticed that component `Shared::BumpCta` was already included in layout `_documentation.erb`, as a slot named `:after` in component `Shared::Sidebar`, but it was not displayed.
What is done in this PR:
- change condition to display this component: favor ready-to-use boolean `resource.data.display_cta`
- render the slot in the component, with `<%= slotted :after %>`
- add basic CSS to keep space between this CTA and the sidebar links 😇 (no dinguerie I swear!)
- set data.slug to 'openapi-specification', used as `utm_content`.
ℹ️  Data `display_cta` is responsible to display the BumpCta component. We would need to change value to false where it's not necessary.
Now:
---
context: [Slack …

Display CTA component with a slot

---

src/_guides/bump-sh-tutorials/documenting-multiple-api-versions.md

this commit contains two things:
- one typo fix in the multi file in same repo example
- suggestion to use a single workflow for the multi branches repo example

blog: small typo and suggestion on multiple git branch workflow

---

src/_data/sidebar.yml
src/_data/sidebars/help.yml
src/_help/specification-support/extensions.md
src/_help/specification-support/meta-tags.md

Hey,
Here's a small PR to help users use the freshly released `x-metaTags`
- I added the page to "Common Elements" as I didn't see it fit in any other part of the global flow. Tell me if you think otherwise 🙏
- I would love to:
- know if it's understandable as explained now, with the multiple examples,
- get a validation of these examples reliability.
- I took the opportunity to sort the pages under "Common Elements" alphabetically in the sidebar. Is it a best practice, and if so, should we do it for every section of the sidebar? (In "Public documentation" for example").
Thanks a lot 💙

Help Center: introducing x-metaTags

---

src/_help/customization-options/index.md
src/_help/hubs/create-and-manage-hubs.md
src/_help/hubs/index.md
src/_help/organizations/organization-access-management.md
src/_help/publish-documentation/branching.md
src/_help/publish-documentation/deploy-and-release-management.md
src/_help/publish-documentation/documentation-access-management.md

In the Help Center, some features restricted to certain plans didn’t display that information. It has now been added where relevant to clarify which plan is required to access them.

Add pricing information for some features

---

src/_help/documentation-experience/markdown-support.md

A little trick by @paulRbr to properly display `=dimension` in a code block in the help center.

Parsing tweak for =dimension

---

src/_partials/_head.erb

When `data.canonical_url`, I noticed that
HTML tag `<link rel="canonical" href="<%= data.canonical_url %>" />` is rendered twice.
canonical URL is already included in logic `<%= seo %>`, thanks to gem `bridgetown-seo-tag`
cf doc https://www.rubydoc.info/gems/bridgetown-seo-tag/6.0.0
for example https://docs.bump.sh/guides/api-basics/api-architecture-diagrams/

SEO: fix canonical_url duplication
