- docs/access-management.md
- docs/api-change-management/index.md
- docs/bump-cli.md
- docs/continuous-integration/github-actions.md
- docs/continuous-integration/index.md
- docs/home.md
- docs/hubs.md
- docs/intro.md
- docs/markdown-support.md
- docs/organizations/single-sign-on-sso.md
- docs/references.md
- docs/specifications-support/asyncapi-support.md
- docusaurus.config.js
- sidebars.js
- added a new 'home' page for the help section
- created a Getting Started section
- moved intro to this new section
> modified home, added a Getting started section

- src/css/custom.css
- src/css/navigation.css
- src/css/variables.css
This applies the same background colors as used on Bump.
> style: define background color for light and dark theme

- src/css/navigation.css
- src/css/variables.css
This PR makes small adjustments regarding borders, paddings and colors.
> style: small nav improvements

- docs/help/getting-started.md
- sidebars.js
Content plan has been added for the getting started page.
Writing content can be done later. Started to prepare a few screenshots too.
> added content plan to getting started page

- src/css/footer.css
> style: make footer closer to bump.sh website footer

- docs/help/specifications-support/asyncapi-support.md
- docs/help/specifications-support/openapi-support.md
Small update to reflect last changes in the original documentation from Polo
> added the recent changes about readonly/writeonly in the doc

- docusaurus.config.js
- src/docusaurus-plugin-fathom/index.js
- src/docusaurus-plugin-intercom/index.js
This PR adds:
- Fathom
- Intercom
Note: the siteId (for Fathom) and appId (for Intercom) values are
incorrect and needs to be changed in the docusaurus.config.js config.
> plugins: add Fathom and Intercom

- docs/help/specifications-support/polymorphism.md
> Fix typo in polymorphism page

- docusaurus.config.js
Will this one be the last PR to make it work? 😂
> Fix logo URL

- src/docusaurus-plugin-fathom/index.js
From Fathom documentation: https://usefathom.com/docs/integrations/spas.
This will fix our current issue with analytics.
> Activate spa=auto to run analytics in single-page mode

- docs/help/custom-domains.md
Trying to improve his doc a little, after reviewing the latest support requests on the topic.
> Update custom domain help

- docs/product-updates/2023-06-03-lightning-fast-api-documentation-rendering.md
This PR updates the product updates #71 for consistency purpose.
> Product updates: New rendering entry title update

- frontend/styles/atoms/details.css
- frontend/styles/index.css
This add styles for the details element.
You can use it by adding this:
```
<details>
<summary>Title of your content</summary>
Your content
</details>
```
> add styles for details

- frontend/styles/atoms/details.css
- frontend/styles/atoms/kbd.css
- frontend/styles/index.css
Just some sweets for copywriting purpose. 🍬 
You can use this element by adding `<kbd>Any text</kbd>` in your `.md` file.
> add style for `kbd` element

- .github/workflows/test.yml
- Gemfile.lock
I forgot to readd the `.github/workflows` folder and it seems it's blocking PRs as there's no test to be executed.
> restore github workflow files

- src/_components/shared/footer.rb
- src/_help/_defaults.yml
- src/_layouts/default.erb
- src/_layouts/help.erb
Got my condition upside-down and footer wasn't shown anymore.
> fix footer render condition

- frontend/styles/pages/help.css
- plugins/builders/helpers.rb
- src/_components/guides/sidebar.erb
- src/_components/guides/sidebar.rb
- src/_components/help/sidebar.css
- src/_components/help/sidebar/item.css
- src/_components/shared/edit_on_github.css
- src/_components/shared/edit_on_github.erb
- src/_components/shared/edit_on_github.rb
- src/_data/site_metadata.yml
- src/_layouts/guide.erb
- src/_layouts/help.erb
- src/images/icons/pencil.svg
As said in title, this puts a link to github file at the bottom of the page.
> help: add edit on github button

- src/_help/index.md
Many dead links on main page on the Help Center, should be fixed now.
> fixed dead links

- src/_product-updates/2020-12-01-custom-domain-for-everyone.md
- src/_product-updates/2021-07-02-bump-diff-from-your-cli.md
- src/_product-updates/2021-09-07-markdown-support.md
- src/_product-updates/2021-10-12-bump-live-preview.md
- src/_product-updates/2022-03-20-documentation-access.md
- src/_product-updates/2022-12-07-improved-access-management.md
- src/_product-updates/2023-01-27-enhanced-specifications-support.md
- src/_product-updates/2023-08-01-custom-code-samples.md
- src/_product-updates/2023-09-28-manual-release.md
- src/_product-updates/2023-10-05-editable-release.md
Might need another pass once #152 and #133 are merged.
> Fix broken links from Help docs structure change

- src/_help/continuous-integration/github-actions.md
Secrets must be used, not environment variables.
> Fix GitHub Action configuration

- src/_redirects
Quick fix for custom-domain redirection
> fixed missing redirection for custom domains

- LICENSE_CC-BY-NC-SA-4.0
- LICENSE_MIT
- README.md
- Code base will be MIT
- Content will be CC BY-NC-SA
> licensing the repository

- src/_product-updates/2023-11-15-seach-engine-performances-enhancement.md
Added a fix to display the missing visual in the PU.
> Fix missing image in product update Search Engine

- src/_guides/api-basics/api-architecture-diagrams.md
Change a link to x-topics documentation
> change_xtopic_link_on_api_architecture_diagram

- src/_help/continuous-integration/cli.md
I was reading the doc and I wanted to click on the link to the GH Action but I bumped on a 404 (pun intended).
> Update GH Action URL

- src/_guides/technical-writing/2024-05-22-enriching-your-openapi-info-documentation-for-understanding.md
> Rename and added canonical URL to the "Enrich OpenAPI info section" guide

- src/_help/organizations/organization-access-management.md
Mention field 'description' available for every SsoConnection.
following https://github.com/bump-sh/docs/pull/265/files#r1699589462
> SSO page: mention descriptions

- src/_data/sidebar.yml
- src/_help/customization-options/login.md
I decided to add a full page (rather than a section on an existing page) to make the option more visible.
I'm considering adding a "wireframe" style screenshot to show what's possible. If that seems relevant... I'd appreciate a mockup :)
> Log in page customization

- src/_guides/openapi/specification/v3.1/documentation/external-documentation.md
Prevents deployment based on copying and pasting the example
> singularise 'versions'

- src/_guides/openapi/specification/v3.1/introduction/what-is-openapi.md
Rewrite for clarity; fixes #293
> Rewrite for clarity; fixes #293

- src/_guides/bump-sh-tutorials/testing-with-microcks.md
Mocking had an automation section and it makes sense for the testing guide to do the same.
> mention how to automate testing for microcks

- src/_guides/bump-sh-tutorials/migrate-from-redocly.md
- src/_guides/bump-sh-tutorials/mocking-with-microcks.md
- src/_guides/bump-sh-tutorials/testing-with-microcks.md
- src/_guides/openapi/augmenting-generated-openapi.md
- src/_guides/openapi/express-api-openapi.md
- src/_help/continuous-integration/github-actions.md
I tweaked a few bits working on other PRs and figured it was worth doing the lot at onces, and making a seperate PR.
> chore: update actions/checkout@v3 to v4

- src/_help/organizations/organization-access-management.md
- src/_help/publish-documentation/documentation-access-management.md
A small update reflecting our recent investigation on the topic. Please let me know if you feel that something is missing.
> Updated rights for maintainer role

- src/_components/shared/third_parties.erb
We are not using the service anymore.
> Remove reo.dev

- src/_guides/bump-sh-tutorials/documenting-multiple-api-versions.md
Added canonical URL
Fixed an URL
Replaced "version" by "branch" when needed.
> Added canonical URL and small fix to Multiple API versions guide

- src/_product-updates/2025-09-29-documentation-enhancements-and-fixes.md
Here's a small product update to share all the smaller things that have been done to improve the API doc experience, alongside larger projects. 🚀
> Product update: enhancements and bug fixes changelog
